### ISSUE TITLE
The bot is missing core assets? 

### ISSUE THREAD

**Issue by Void-Man-1** [Eden998/Match-Masters-Bot#1]
Upon installing all nesessery components to run the .py script and launching it, terminal says that some assets of the script are missing. 

```
PS C:\Users\User\Desktop\Match-Masters-Bot-main\Match-Masters-Bot-main> python test.py
[ WARN:0@0.071] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/red.png'): can't open/read file: check file path/integrity
[ WARN:0@0.075] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/green.png'): can't open/read file: check file path/integrity
[ WARN:0@0.080] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/yellow.png'): can't open/read file: check file path/integrity
[ WARN:0@0.085] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/purple.png'): can't open/read file: check file path/integrity
[ WARN:0@0.089] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/blue.png'): can't open/read file: check file path/integrity
[ WARN:0@0.094] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/orange.png'): can't open/read file: check file path/integrity
[ WARN:0@0.097] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/horizonal_purple_arrow.png'): can't open/read file: check file path/integrity
[ WARN:0@0.102] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/vertical_blue_arrow.png'): can't open/read file: check file path/integrity
[ WARN:0@0.107] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/green_bomb.png'): can't open/read file: check file path/integrity
[ WARN:0@0.112] global loadsave.cpp:248 cv::findDecoder imread_('assets/general/green_lightning.png'): can't open/read file: check file path/integrity
[ WARN:0@0.116] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/bounty/bounty.png'): can't open/read file: check file path/integrity
[ WARN:0@0.121] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/leafs/leaf.png'): can't open/read file: check file path/integrity
[ WARN:0@0.125] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/purple_gem/purple_gem_4.png'): can't open/read file: check file path/integrity
[ WARN:0@0.130] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/purple_gem/purple_gem_5.png'): can't open/read file: check file path/integrity
[ WARN:0@0.134] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/red_blue/red_blue.png'): can't open/read file: check file path/integrity
[ WARN:0@0.139] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/chest/chest.png'): can't open/read file: check file path/integrity
[ WARN:0@0.143] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/chest/chest2.png'): can't open/read file: check file path/integrity
[ WARN:0@0.148] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/frozen/frozen_horizonal_red_arrow.png'): can't open/read file: check file path/integrity
[ WARN:0@0.152] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/frozen/frozen_vertical_purple_arrow.png'): can't open/read file: check file path/integrity
[ WARN:0@0.157] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/frozen/frozen_blue_bomb.png'): can't open/read file: check file path/integrity
[ WARN:0@0.162] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/frozen/frozen_red_lightning.png'): can't open/read file: check file path/integrity
[ WARN:0@0.167] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/fireworks/left_firework.png'): can't open/read file: check file path/integrity
[ WARN:0@0.171] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/fireworks/right_firework.png'): can't open/read file: check file path/integrity
[ WARN:0@0.176] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/fireworks/down_firework.png'): can't open/read file: check file path/integrity
[ WARN:0@0.180] global loadsave.cpp:248 cv::findDecoder imread_('assets/modes/fireworks/up_firework.png'): can't open/read file: check file path/integrity
```

If the warning is ignored and the button "Check best move" is clicked while the game is opened in blue stacks emulator the following error occurs

```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Match-Masters-Bot-main\Match-Masters-Bot-main\test.py", line 617, in button_clicked
    self.check_best_move()
  File "C:\Users\User\Desktop\Match-Masters-Bot-main\Match-Masters-Bot-main\test.py", line 624, in check_best_move
    game_board, special_game_board = update_board_2(game_board, special_game_board)
  File "C:\Users\User\Desktop\Match-Masters-Bot-main\Match-Masters-Bot-main\test.py", line 179, in update_board_2
    img_color = pyautogui.screenshot(("Debug/" + curr_time + ".png"), region=(left, up, width, height))  # DEBUG
  File "C:\Users\User\anaconda3\lib\site-packages\pyscreeze\__init__.py", line 518, in _screenshot_win32
    im.save(imageFilename)
  File "C:\Users\User\anaconda3\lib\site-packages\PIL\Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'Debug/2023-07-09 17_28_43.png'
PS C:\Users\User\Desktop\Match-Masters-Bot-main\Match-Masters-Bot-main>
```

**Comment by DARKM00N1337** [comment]
I have this problem too

**Comment by Lahjamies666** [comment]
It's because the script is trying to find image files to run the script which are not included in this source, you will have to crack the app and find the .png files.

**Comment by Anubiiiiiiiiiis** [comment]
How i can download the .png? I must open an APK with tool? I tried with decompiling the APK but there aren't 

![image](https://github.com/Eden998/Match-Masters-Bot/assets/130409955/3ce0c5d2-e01f-4dc3-ac0e-02610323575b)

**Comment by MrShakeSs** [comment]
Somebody got the assets or nah

**Comment by NobilityDeviant** [comment]
just take pictures yourself and add them in a folder called assets
it's just looking for pieces pictures as far as I can see

**Comment by MrShakeSs** [comment]
> just take pictures yourself and add them in a folder called assets it's just looking for pieces pictures as far as I can see

I dont know a way to take consistent pictures

**Comment by NobilityDeviant** [comment]
> > just take pictures yourself and add them in a folder called assets it's just looking for pieces pictures as far as I can see
> 
> I dont know a way to take consistent pictures

Look at this image: [image_recognition.png](https://github.com/Eden998/Match-Masters-Bot/blob/main/images/image_recognition.png)

It's just a square around the piece. You need a screenshot of every single piece.

Go look up a couple youtube videos and screenshot everything you can find in the code.

No one else will do it for you, but this should be all the knowledge you need.
